<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaPolice.Abstractions\CaPolice.Abstractions.csproj" />
  </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Azure.Core" Version="1.62.0" />
        <PackageReference Include="JsonSchema.Net" Version="7.2.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="10.0.11" />
        <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11" />
        <PackageReference Include="System.Text.Json" Version="10.0.11" />
    </ItemGroup>

</Project>
